### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by exlulu** [ImYrS/aliyun-auto-signin#1]
Ubuntu 20.04.4 LTS
Python 3.11.2
Traceback (most recent call last):
  File "/home/lulu/aliyun-auto-signin/app.py", line 14, in <module>
    from configobj import ConfigObj
ModuleNotFoundError: No module named 'configobj'

Python 3.8.10
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    def update_access_token(refresh_token: str) -> bool | dict:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Python 2.7.18
  File "app.py", line 18
    def update_access_token(refresh_token: str) -> bool | dict:
                                         ^
SyntaxError: invalid syntax

**Comment by ImYrS** [comment]
python 要求 >= 3.10

pip install configobj requests

example.config.ini => config.ini

readme 还没写 晚点补上

**Comment by exlulu** [comment]
> python 要求 >= 3.10
> 
> pip install configobj requests
> 
> example.config.ini => config.ini
> 
> readme 还没写 晚点补上

Python 3.11.2
Requirement already satisfied: configobj in /usr/lib/python3/dist-packages (5.0.6)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.22.0)

依然提示
Traceback (most recent call last):
File "/home/lulu/aliyun-auto-signin/app.py", line 14, in
from configobj import ConfigObj
ModuleNotFoundError: No module named 'configobj'

**Comment by exlulu** [comment]
> python 要求 >= 3.10
> 
> pip install configobj requests
> 
> example.config.ini => config.ini
> 
> readme 还没写 晚点补上

谢谢大佬，已解决，装的是python3.11 需要用pip3.11 install来装依然才行
