### ISSUE TITLE
无效语法

### ISSUE THREAD

**Issue by Nikkiiw** [ImYrS/aliyun-auto-signin#11]
您好！运行时报语法失效啦！

![image](https://user-images.githubusercontent.com/91337184/221429748-514ff843-a8d6-43a4-876b-14670c44018d.png)

**Comment by ImYrS** [comment]
@Nikkiiw python 要求 3.10 以上

**Comment by Nikkiiw** [comment]
额,谢谢！ 我是宝塔里的python项目管理器....应该是没激活环境，我再研究下

**Comment by ImYrS** [comment]
@Nikkiiw 1. 自己编译 3.10 环境
2. 用旧版 python 兼容分支，但功能不是最新的
3. 用 Action

**Comment by Nikkiiw** [comment]
谢谢，git action已经成功了，想测试一下dingtalk...无论如何感谢这么晚还在回复！

**Comment by ImYrS** [comment]
@Nikkiiw 不用谢
