### ISSUE TITLE
Action 的参考配置前面多了空格

### ISSUE THREAD

**Issue by exlulu** [ImYrS/aliyun-auto-signin#18]
不知道大佬是故意的还是不小心的，哈哈哈哈哈
直接复制粘贴[参考配置](https://github.com/ImYrS/aliyun-auto-signin/blob/main/How-To-Use-Action.md#编写-action-配置)运行Action会报错

**Comment by ImYrS** [comment]
是...不小心的

但是我自己测试没发现这个问题诶

**Comment by 237686270** [comment]
那里啊，纯小白不会能搞到一天都不行

**Comment by monSteRhhe** [comment]
> 那里啊，纯小白不会能搞到一天都不行

本地用vscode那样的编辑器，创建一个yml打开，直接复制参考配置的全部内容粘贴进去，会发现从第二行开始行首都会有一个空格，去掉就可以了

**Comment by 237686270** [comment]
> > 那里啊，纯小白不会能搞到一天都不行
> 
> 
> 
> 本地用vscode那样的编辑器，创建一个yml打开，直接复制参考配置的全部内容粘贴进去，会发现从第二行开始行首都会有一个空格，去掉就可以了

我用的是在线那个怎么能都不行

**Comment by exlulu** [comment]
> 那里啊，纯小白不会能搞到一天都不行

你是做到哪一步？如果能运行，那贴一下log看看哪里报错

**Comment by ImYrS** [comment]
should fixed in [04f3868](https://github.com/ImYrS/aliyun-auto-signin/commit/04f386831116d6889bca2185ad6101fa6e035ba0)
