### ISSUE TITLE
Actions里面是空着还是要在配置自动啊

### ISSUE THREAD

**Issue by 237686270** [ImYrS/aliyun-auto-signin#19]
按照你的教程操作完了，Actions里面是空着还是要在配置自动啊。到这步实在不会了

**Comment by 237686270** [comment]
而且不自动运行啊。actions里面也没有日志

**Comment by ImYrS** [comment]
是在 .github/workflows/ 下面新建文件... 你路径是中文的，浏览器翻译用过头了

**Comment by 237686270** [comment]
> 是在 .github/workflows/ 下面新建文件... 你路径是中文的，浏览器翻译用过头了

意思是不能有中文路径，然后就.github/workflows/signin.yml里把你的配置粘贴进去是吗，然后就是配置 GitHub Secrets 里面按照你的操作来，是直接填tokens还是要REFRESH_TOKENS空格再填tokens啊，
然后Action就是自动启动这个里不用在配置东西了是吗![image](https://user-images.githubusercontent.com/26134140/222954255-ea0985b4-c94f-4e52-9a10-a361b5a70b9c.jpeg)

**Comment by ImYrS** [comment]
@237686270 对，正确配置后 actions 这里会出现 Aliyun Signin 之类的。可以等他自动运行，也可以手动提前运行

**Comment by 237686270** [comment]
> @237686270 对，正确配置后 actions 这里会出现 Aliyun Signin 之类的。可以等他自动运行，也可以手动提前运行

配置 GitHub Secrets 里面按照你的操作来，是直接填tokens    还是要REFRESH_TOKENS空格再填tokens啊，

**Comment by exlulu** [comment]
> > @237686270 对，正确配置后 actions 这里会出现 Aliyun Signin 之类的。可以等他自动运行，也可以手动提前运行
> 
> 配置 GitHub Secrets 里面按照你的操作来，是直接填tokens 还是要REFRESH_TOKENS空格再填tokens啊，

在仓库的 Settings -> Secrets and Variables -> Actions，点进右面绿色New repository secret按钮，Name*填[配置 GitHub Secrets](https://github.com/ImYrS/aliyun-auto-signin/blob/main/How-To-Use-Action.md#配置-github-secrets)的内容，如必选的"REFRESH_TOKENS"，不需要引号，Secret*则填对应的值，如对应的refresh token，然后点击绿色Add secret按钮，如要推送，则再点进右面绿色New repository secret按钮，继续添加需要的推送和对应的值

**Comment by exlulu** [comment]
> > 是在 .github/workflows/ 下面新建文件... 你路径是中文的，浏览器翻译用过头了
> 
> 意思是不能有中文路径，然后就.github/workflows/signin.yml里把你的配置粘贴进去是吗，然后就是配置 GitHub Secrets 里面按照你的操作来，是直接填tokens还是要REFRESH_TOKENS空格再填tokens啊， 然后Action就是自动启动这个里不用在配置东西了是吗!

按需修改signin.yml里面16行的PUSH_TYPES，默认是使用telegram和smtp这两个推送，支持: dingtalk, serverchan, pushdeer, telegram, pushplus, smtp

**Comment by 237686270** [comment]
> > > @237686270 对，正确配置后 actions 这里会出现 Aliyun Signin 之类的。可以等他自动运行，也可以手动提前运行
> 
> > 
> 
> > 配置 GitHub Secrets 里面按照你的操作来，是直接填tokens 还是要REFRESH_TOKENS空格再填tokens啊，
> 
> 
> 
> 在仓库的 Settings -> Secrets and Variables -> Actions，点进右面绿色New repository secret按钮，Name填[配置 GitHub Secrets](https://github.com/ImYrS/aliyun-auto-signin/blob/main/How-To-Use-Action.md#配置-github-secrets)的内容，如必选的"REFRESH_TOKENS"，不需要引号，Secret则填对应的值，如对应的refresh token，然后点击绿色Add secret按钮，如要推送，则再点进右面绿色New repository secret按钮，继续添加需要的推送和对应的值

万分感谢我去试试

**Comment by 237686270** [comment]
> > > @237686270 对，正确配置后 actions 这里会出现 Aliyun Signin 之类的。可以等他自动运行，也可以手动提前运行
> > 
> > 
> > 配置 GitHub Secrets 里面按照你的操作来，是直接填tokens 还是要REFRESH_TOKENS空格再填tokens啊，
> 
> 在仓库的 Settings -> Secrets and Variables -> Actions，点进右面绿色New repository secret按钮，Name填[配置 GitHub Secrets](https://github.com/ImYrS/aliyun-auto-signin/blob/main/How-To-Use-Action.md#%E9%85%8D%E7%BD%AE-github-secrets)的内容，如必选的"REFRESH_TOKENS"，不需要引号，Secret则填对应的值，如对应的refresh token，然后点击绿色Add secret按钮，如要推送，则再点进右面绿色New repository secret按钮，继续添加需要的推送和对应的值

不行啊。NAME填写配置的内容提示，文件名重复啊

**Comment by 237686270** [comment]
> > > > @237686270 对，正确配置后 actions 这里会出现 Aliyun Signin 之类的。可以等他自动运行，也可以手动提前运行
> > 
> > 
> > > 
> > 
> > 
> > > 配置 GitHub Secrets 里面按照你的操作来，是直接填tokens 还是要REFRESH_TOKENS空格再填tokens啊，
> > 
> > 
> > 在仓库的 Settings -> Secrets and Variables -> Actions，点进右面绿色New repository secret按钮，Name填[配置 GitHub Secrets](https://github.com/ImYrS/aliyun-auto-signin/blob/main/How-To-Use-Action.md#%E9%85%8D%E7%BD%AE-github-secrets)的内容，如必选的"REFRESH_TOKENS"，不需要引号，Secret则填对应的值，如对应的refresh token，然后点击绿色Add secret按钮，如要推送，则再点进右面绿色New repository secret按钮，继续添加需要的推送和对应的值
> 
> 万分感谢我去试试

出现actions里面的任务了，但是提示这个下面这个图
![360截图-718017984](https://user-images.githubusercontent.com/26134140/222967186-f11be01c-7c55-40f8-9481-6dacb55b4b9e.jpg)
