### ISSUE TITLE
大佬，能不能辛苦加个推送通知，比如钉钉之类的，辛苦，辛苦

### ISSUE THREAD

**Issue by nhddhr** [ImYrS/aliyun-auto-signin#2]

**Comment by nhddhr** [comment]
如果能再加个多账号就更完美了，嘿嘿

**Comment by ImYrS** [comment]
推送有时间会写一下, 欢迎 PR.

多账号不会在此项目添加, 可以参考 readme.

**Comment by ImYrS** [comment]
钉钉机器人推送已实现在 [40b5148](https://github.com/ImYrS/aliyun-auto-signin/commit/40b51481fca564004da8965c003ea90645ec14ce)
