### ISSUE TITLE
填写PUSHPLUS_TOKEN后不走pushplus推送

### ISSUE THREAD

**Issue by xuange-dada** [ImYrS/aliyun-auto-signin#20]
2023-03-05 07:38:42,666 - app.py:92 - INFO: [[1](https://github.com/xuange-dada/aliyun-signin-action/actions/runs/4334995469/jobs/7569256508#step:4:1)3*****8[2](https://github.com/xuange-dada/aliyun-signin-action/actions/runs/4334995469/jobs/7569256508#step:4:2)] 签到成功, 本月累计签到 5 天.
202[3](https://github.com/xuange-dada/aliyun-signin-action/actions/runs/4334995469/jobs/7569256508#step:4:3)-03-05 07:38:[4](https://github.com/xuange-dada/aliyun-signin-action/actions/runs/4334995469/jobs/7569256508#step:4:4)2,666 - app.py:93 - INFO: [13******2] 本次签到 无奖励
2023-03-0[5](https://github.com/xuange-dada/aliyun-signin-action/actions/runs/4334995469/jobs/7569256508#step:4:5) 07:38:42,[6](https://github.com/xuange-dada/aliyun-signin-action/actions/runs/4334995469/jobs/7569256508#step:4:6)66 - telegram.py:[7](https://github.com/xuange-dada/aliyun-signin-action/actions/runs/4334995469/jobs/7569256508#step:4:7)[8](https://github.com/xuange-dada/aliyun-signin-action/actions/runs/4334995469/jobs/7569256508#step:4:8) - ERROR: Telegram 推送参数配置不完整
2023-03-05 07:38:42,666 - smtp.py:86 - ERROR: SMTP 推送参数配置不完整

**Comment by 237686270** [comment]
你怎么设置的，为啥我设置的不自动签到啊，aciton里你设置自动启动任务了吗，配置 GitHub Secrets，是直接填token还是要复制REFRESH_TOKENS这个在后面再填tonken

**Comment by ImYrS** [comment]
要在 action 的 signin.yml 里面改 push_types
