### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by chenyong0709** [ImYrS/aliyun-auto-signin#26]
![QQ图片20230311154512](https://user-images.githubusercontent.com/97508075/224472148-3a5cdd3a-7128-476d-8af2-4a3f5931c5bf.png)
![QQ图片20230311154555](https://user-images.githubusercontent.com/97508075/224472172-c6d7d765-8620-47e7-b16d-a49abbeb9b04.png)

**Comment by ImYrS** [comment]
似乎是更新 GitHub Secrets 里的问题，可能是 GitHub Token 问题？
@fuwt 是否有时间看下，做一个错误处理

**Comment by chenyong0709** [comment]
> 好像是更新 GitHub Secrets 里的问题，可能是 GitHub Token 问题？ @fuwt是不是有时间看下面，做一个错误处理

app打开是已经签到了。但不知道怎么还报这么一个错误

**Comment by 237686270** [comment]
GP_TOKEN: ${{ secrets.GP_TOKEN}}
大佬问下这个新加的用来干啥的啊，我没设置，不影响现在使用吧。

**Comment by ImYrS** [comment]
@237686270 用于自动更新 github secrets 见 v1.3.4

**Comment by 237686270** [comment]
> @237686270 用于自动更新 github secrets 见 v1.3.4

我是用的GitHub 自动的，这个可以自动更新吗，你主页上说的按你主页操作的的，可以自动更新，我这个就是不行，我从新改的代码

**Comment by ImYrS** [comment]
@237686270 这个因为改写了 action 文件，所以无法自动更新。签到脚本本身是可以自动更新的

**Comment by 237686270** [comment]
> @237686270 这个因为改写了 action 文件，所以无法自动更新。签到脚本本身是可以自动更新的

那我还用改什么嘛？我把新代码改完了，以后会自动更新吗？别的还有需要改的吗？谢谢大佬耐心解答。

**Comment by ImYrS** [comment]
@237686270 如果 action 不改, 或者不涉及配置项更改的情况, 都不需要动
