### ISSUE TITLE
青龙订阅运行：No module named 'modules'

### ISSUE THREAD

**Issue by thinker226** [ImYrS/aliyun-auto-signin#31]
Traceback (most recent call last):
  File "/ql/data/scripts/ImYrS_aliyun-auto-signin/app.py", line 18, in <module>
    from modules import dingtalk, serverchan, pushdeer, telegram, pushplus, smtp
ModuleNotFoundError: No module named 'modules'

报错如上，请教

**Comment by ImYrS** [comment]
@thinker226 确认一下脚本运行的路径, 如果不是在项目文件夹里运行, 就读不到 modules 的模块

**Comment by thinker226** [comment]
> @thinker226 确认一下脚本运行的路径, 如果不是在项目文件夹里运行, 就读不到 modules 的模块
我是最新版的青龙，订阅之后生成的一个任务：task ImYrS_aliyun-auto-signin/app.py
翻看了文件夹，ImYrS_aliyun-auto-signin名的文件夹在"/ql/data/的REPO和SCRIPTS下都有，app.py的文件也都存在

**Comment by ImYrS** [comment]
在 `app.py` 的这个文件的目录里, 新建一个 `temp.py` 内容如下
```
from os import getcwd

print(getcwd())
```
用来输出当前运行目录, 再用你的定时任务运行这个 `temp.py` 看看输出结果是什么

**Comment by thinker226** [comment]
> 在 `app.py` 的这个文件的目录里, 新建一个 `temp.py` 内容如下
> 
> ```
> from os import getcwd
> 
> print(getcwd())
> ```
> 
> 用来输出当前运行目录, 再用你的定时任务运行这个 `temp.py` 看看输出结果是什么
## 开始执行... 2023-03-12 21:12:28

/ql/data/scripts/ImYrS_aliyun-auto-signin


## 执行结束... 2023-03-12 21:12:28  耗时 0 秒　　　
无错运行，不过无法看出是不是成功了。config.ini在repo的文件夹里我已经把阿里云盘的CK添加的了。

**Comment by ImYrS** [comment]
@thinker226 无能为力, 没用过这个面板. 思路就是判断运行路径问题, 或者是模块冲突

**Comment by thinker226** [comment]
> @thinker226 无能为力, 没用过这个面板. 思路就是判断运行路径问题, 或者是模块冲突

好的 感谢你的耐心帮助
