### ISSUE TITLE
青龙面板运行，出错

### ISSUE THREAD

**Issue by iStone1984** [ImYrS/aliyun-auto-signin#32]
青龙面板运行，出错提示信息如下：
## 开始执行... 2023-03-15 19:13:32

Traceback (most recent call last):
  File "/ql/data/scripts/ImYrS_aliyun-auto-signin/app.py", line 18, in <module>
    from modules import dingtalk, serverchan, pushdeer, telegram, pushplus, smtp
ImportError: cannot import name 'dingtalk' from 'modules' (/usr/local/lib/python3.10/site-packages/modules.py)

## 执行结束... 2023-03-15 19:13:37  耗时 5 秒

**Comment by ImYrS** [comment]
@iStone1984 modules 模块名冲突

不熟悉 python 建议改用 action
