### ISSUE TITLE
日志显示推送成功, 但实际上没有推送

### ISSUE THREAD

**Issue by ImYrS** [ImYrS/aliyun-auto-signin#37]
推送也是正常的，运行情况显示推送也是成功，就是没有推送来

_Originally posted by @Zxr112553438 in https://github.com/ImYrS/aliyun-auto-signin/issues/35#issuecomment-1477231660_

**Comment by ImYrS** [comment]
@Zxr112553438 今天有时间重新运行一下 action, 或者等明天自动运行, 看看是不是还是显示推送成功, 但其实没有推送

**Comment by Zxr112553438** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ImYrS/aliyun-auto-signin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月21日(星期二) 中午1:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ImYrS/aliyun-auto-signin] 日志显示推送成功, 但实际上没有推送 (Issue #37)





 
@Zxr112553438 今天有时间重新运行一下 action, 或者等明天自动运行, 看看是不是还是显示推送成功, 但其实没有推送
 
—好的

**Comment by Zxr112553438** [comment]
@ImYrS 手动运行了，显示pushplus推送成功，实际pushplus没推送

**Comment by Zxr112553438** [comment]
![image](https://user-images.githubusercontent.com/93114244/226527849-49ed2700-e351-41ac-a1fd-4757c77c3e92.png)

**Comment by Zxr112553438** [comment]
![image](https://user-images.githubusercontent.com/93114244/226527929-0fca3793-7562-4e4c-99a7-af3721bce5fc.png)

**Comment by ImYrS** [comment]
@Zxr112553438 你有没有其他用 pushplus 的项目，可以成功推送吗

**Comment by Zxr112553438** [comment]
@ImYrS 有其他项目，能成功推送

**Comment by ImYrS** [comment]
好，晚点有时间我看下

**Comment by ImYrS** [comment]
@Zxr112553438 这两天还有出现无法正常签到的情况吗，比如签到无奖励但其实有，或者是显示有奖励但实际未领取？

**Comment by ImYrS** [comment]
@exlulu 没问题，我到时候看下

**Comment by exlulu** [comment]
> @exlulu 没问题，我到时候看下

感谢大佬辛勤更新
这个是PP的文档，API是有不同返回代码的，但是我不会写这个判断，哈，辛苦大佬了
https://www.pushplus.plus/doc/guide/code.html

**Comment by ImYrS** [comment]
@Zxr112553438 方便的话, 把你的签到 action 的 yml 配置改一下
```
 - uses: ImYrS/aliyun-auto-signin@main
```
最后面的 `@main` 改为 `@beta`

然后重新运行 action 看下输出日志, 是否还是显示 pushplus 推送成功, 但实际没有推送? 或者是显示推送失败和原因?

**Comment by Zxr112553438** [comment]
@ImYrS 好的，现在搞

**Comment by Zxr112553438** [comment]
![1679635049438](https://user-images.githubusercontent.com/93114244/227430949-3e3b57ad-cbbf-4236-9437-956dad69cf4a.jpg)
是这样吧？

**Comment by ImYrS** [comment]
@Zxr112553438 @main 改为 @beta 不是加上去

**Comment by Zxr112553438** [comment]
![Uploading image.png…]() 
@ImYrS

**Comment by ImYrS** [comment]
图片没上传成功

**Comment by Zxr112553438** [comment]
![image](https://user-images.githubusercontent.com/93114244/227431789-6f473994-b049-4f53-9609-1406f13a7603.png)

**Comment by Zxr112553438** [comment]
![image](https://user-images.githubusercontent.com/93114244/227431871-9f7bf170-50b2-44e5-8994-28281f0d3125.png)

**Comment by Zxr112553438** [comment]
![image](https://user-images.githubusercontent.com/93114244/227431904-23527c42-2e63-4dca-916f-3506fc61d439.png)

**Comment by ImYrS** [comment]
应该就是你 pushplus 配置的 token 错了, 重新设置一下试试

**Comment by Zxr112553438** [comment]
推送有了，之后再看看奖励会不会漏领了

**Comment by ImYrS** [comment]
@Zxr112553438 你可以先保持在 @beta ，奖励漏领这个也做了处理，但还没确认解决，可以观望几天
