### ISSUE TITLE
建议增加“pushplus”的一对多消息

### ISSUE THREAD

**Issue by yzfycz** [ImYrS/aliyun-auto-signin#38]
因朋友的账号和自己的账号挂在一起，翻了一下配置文件没发现填“pushplus”一对多的地方，建议增加一个一对多推送的功能。

**Comment by ImYrS** [comment]
参考 #29 , 此功能需要重构配置文件结构, 而且需求过于小众, 不会被实现.

可以通过配置多个 GitHub 仓库的方式实现多用户且独立推送的功能
