### ISSUE TITLE
存在潜在的签到奖励领取问题

### ISSUE THREAD

**Issue by ImYrS** [ImYrS/aliyun-auto-signin#39]
基于 #35 和调查, 目前可能存在一下问题:
- 日志和推送显示签到成功, 但实际未领取奖励
- 日志和推送显示今日无奖励, 但可以在阿里云盘客户端手动领取

不能 100% 复现, 经测试在同时间同平台同签到天数情况下存在一个帐号可以自动领取另一个则不可以的异常行为.

等待跟进, 如有其他类似情况或细节, 欢迎反馈

**Comment by GitCourser** [comment]
这问题我好像见过
在脚本运行前,手动在客户端签到但不领奖(签到是自动的,进页面就自动签到,但领奖是需要手动点那个领取按钮),
然后运行脚本会提示"签到成功但无奖励", 然后再去客户端签到页面查看,奖励还在那里,手动点领取才会领取

**Comment by ImYrS** [comment]
@GitCourser 对的，是这个问题。但是没 100% 定位问题。目前猜测是签到接口参数变动导致的，已经做了处理，这几天会发一个新的 release 看看大家反馈如何。

**Comment by ImYrS** [comment]
应在 [v1.4.5](https://github.com/ImYrS/aliyun-auto-signin/releases/tag/v1.4.5) 中被修复

**Comment by GitCourser** [comment]
这个问题好像没解决, 而且是可以复现的
复现操作:
在运行脚本前, 手动去客户端签到但不领奖, 然后运行脚本, 脚本不会领奖提示无奖励

**Comment by ImYrS** [comment]
@GitCourser 貌似只发现延期卡是存在可以单独领取的, 其他奖励都是打开签到页面就自动领取了

**Comment by GitCourser** [comment]
昨天测试是延期卡,前几天测试过影音卡,这两种都不是自动领取
今天是vip卡,可惜测试不了,没有提前进去,被脚本先领了....
下次有vip卡我提前进去试下

**Comment by ImYrS** [comment]
@GitCourser 我这边挂的签到一直是可以自动领取啊，只遇到过一次需要手动领取的。晚点试下你这个复现思路

**Comment by GitCourser** [comment]
可能我没说清楚, 用脚本是能自动领取 (只要是脚本先运行肯定就能领奖)

我说的是手动签到领奖其实是两个步骤, 进了签到页面后直接返回或者点那个叉实际是不会领取的, 必须手动点领取按钮
所以在脚本运行之前, 先手动进签到页面又不领奖, 后面再运行脚本就会提示无奖励, 那时脚本不管运行多少次都不会领奖, 只能手动去签到页面领奖

不知道这个说清楚了没

**Comment by Zxr112553438** [comment]
![image](https://user-images.githubusercontent.com/93114244/229014833-73eac934-4a5b-43ac-b412-9431b79b25c2.png)
今天运行报错，去网盘看了，签到任务做了 @ImYrS

**Comment by ImYrS** [comment]
应在 [v1.5.0](https://github.com/ImYrS/aliyun-auto-signin/releases/tag/v1.5.0) 修复
