### ISSUE TITLE
不能定时执行

### ISSUE THREAD

**Issue by rkdawn** [ImYrS/aliyun-auto-signin#42]
配置好了，不能定时执行，手动可以，不知道问题在哪。

**Comment by ImYrS** [comment]
不要用中文翻译.

你的文件路径应该是 `.github/workflows/xxx.yml`

**Comment by rkdawn** [comment]
> 不要用中文翻译.
> 
> 你的文件路径应该是 `.github/workflows/xxx.yml`

非常感谢，已经解决，我说看着怎么怪怪的。
