### ISSUE TITLE
是否可以增加go-cqhttp推送方式

### ISSUE THREAD

**Issue by jattaHIT** [ImYrS/aliyun-auto-signin#43]
是否可以增加调用go-cqhttp推送的方式？

go-cqhttp开放文档（私聊推送部分）：
https://docs.go-cqhttp.org/api/#%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF

感谢作者的辛苦付出！

**Comment by ImYrS** [comment]
似乎有些复杂，有时间研究下，可能不会实现。

**Comment by jattaHIT** [comment]
> 似乎有些复杂，有时间研究下，可能不会实现。

好的 感谢作者～如果可以实现的话，那就太好了，因为我不太常用其他推送方式，比较习惯QQ…不能实现也无妨～

下面是我自己的一点见解，希望能有帮助。

go-cqhttp运行时会开放一个api请求端口，可以使用GET方法调用，http://ip:端口/send_private_msg?user_id=被通知的QQ号&message=通知内容&access_token=秘钥（如果设置了的话）

需要用户自定义的参数有：
①api的url地址
②被通知qq号
③秘钥（如果设置了的话）

**Comment by ImYrS** [comment]
已在 [v1.5.0](https://github.com/ImYrS/aliyun-auto-signin/releases/tag/v1.5.0) 添加, 未经测试. 有问题的话请另开 issue 并协助检查
