### ISSUE TITLE
go-cqhttp 推送错误

### ISSUE THREAD

**Issue by jattaHIT** [ImYrS/aliyun-auto-signin#46]
报错信息：
2023-03-31 06:18:35,215 - cqhttp.py:77 - ERROR: go-cqhttp 推送失败, 错误信息: 'cqhttp_access_token'

处理办法：
①服务端取消cqhttp_access_token验证，删除CQHTTP_ACCESS_TOKEN，运行后仍报错同上；
②经排查，发现源码 app.py 第307行代码中'gcqhttp_access_token': environ['CQHTTP_ACCESS_TOKEN'], 多了开头字母‘g’。
③ fork 并修改，workflows 修改为fork后仓库调试仍然报错同上。
④将 cqhttp.py fork至本地python环境测试，定义相关变量，可推送测试消息成功，附图如下。

![本地环境测试](https://img.beihai.one/i/2023/03/31/Snipaste_2023-03-31_14-55-37.webp)
![消息推送成功](https://img.beihai.one/i/2023/03/31/Screenshot_2023_0331_145548.webp)

如需要，可提供服务器地址、qq及token

**Comment by ImYrS** [comment]
已经在 [4dd7a70](https://github.com/ImYrS/aliyun-auto-signin/commit/4dd7a70cfbbeeb36d671dbac0d9a59c7acd6485d) 修复

你可以尝试把你的 `.github/workflows/xxx.yml` 配置文件里面
```
 - uses: ImYrS/aliyun-auto-signin@main
```
最后面的 `@main` 改为 `@beta` 切换到实时分支而不是使用最新的 release. 然后运行 action 查看运行结果.

**Comment by jattaHIT** [comment]
> 已经在 [4dd7a70](https://github.com/ImYrS/aliyun-auto-signin/commit/4dd7a70cfbbeeb36d671dbac0d9a59c7acd6485d) 修复
> 
> 你可以尝试把你的 `.github/workflows/xxx.yml` 配置文件里面
> 
> ```
>  - uses: ImYrS/aliyun-auto-signin@main
> ```
> 
> 最后面的 `@main` 改为 `@beta` 切换到实时分支而不是使用最新的 release. 然后运行 action 查看运行结果.

测试go-cqhttp推送成功~
感谢作者的付出！
![image](https://user-images.githubusercontent.com/92134317/229054826-d676c413-67ea-4710-b74b-475a9f4b7f25.png)
