### ISSUE TITLE
添加仅签到不领取奖励功能

### ISSUE THREAD

**Issue by guzp** [ImYrS/aliyun-auto-signin#47]
想象一个问题，并不是每天都需要用到阿里云的吧。那么签到后的vip 延期卡 也就只有在需要的时候才会领取使用。
所以 签到之后的领取能不能设为可选，默认只签到

**Comment by ImYrS** [comment]
有时间添加一个 flag 控制这个行为, 但不一定有效:
- 阿里云盘对签到奖励似乎有领取时间限制
- 之前的签到接口只有一个, 现在变成两个, 不能保证只签到不领取

**Comment by guzp** [comment]
月底最后一天不领确实会浪费，所以程序上可以设计最后一天自动领所有。
有两个选择：  1.最后一天不领浪费    2.程序自动领取但领取当天并没有使用 想使用的时候发现没有了
你会怎么选择

**Comment by guzp** [comment]
最后一天自动领取难以实现大不了人工领取，总好过想用的时候没得用  我个人偏向于默认只签到

**Comment by GitCourser** [comment]
领取倒是简单, 今天1.5新版加的`sign_in_reward`这个接口应该只管领取, 最后一天改天数参数循环下就能领之前所有
但问题是`sign_in_list`这个接口是连签到带领取的
只能等作者@ImYrS抓那个只签到不领取的接口了

ps: 顺便问下@ImYrS不root有法抓包吗, 模拟器里运行不了, 手机又没root

**Comment by ImYrS** [comment]
> 领取倒是简单, 今天1.5新版加的`sign_in_reward`这个接口应该只管领取, 最后一天改天数参数循环下就能领之前所有 但问题是`sign_in_list`这个接口是连签到带领取的 只能等作者@ImYrS抓那个只签到不领取的接口了

`sign_in_reward` 这个接口是新的, 专门负责领取.
`sign_in_list` 这个接口是可以携带 `{"isReward": true}` 参数的. 如果参数是 `true` 也可以直接签到. 但是如果是当天用 `false` 参数请求过这个接口 (也就是手机端打开签到页面), 那再用 `true` 请求会发现这个接口返回的当天奖励是空的. 所以才有了这个 bug.

其实在这之前 `isReward` 这个参数都没有, 打开直接签到并领取. 后来加了参数, 又加了新接口, 奇奇怪怪.

**Comment by ImYrS** [comment]
> 领取倒是简单, 今天1.5新版加的`sign_in_reward`这个接口应该只管领取, 最后一天改天数参数循环下就能领之前所有 但问题是`sign_in_list`这个接口是连签到带领取的 只能等作者@ImYrS抓那个只签到不领取的接口了

但是现在也没确定这个 `sign_in_reward` 的参数这个数字, 指的是几号, 还是累计签到多少天. 还得需要时间测试...

**Comment by GitCourser** [comment]
我刚才用手动签到不领取的情况下, `sign_in_reward`接口中`signInDay`改成`31`能把今天的奖励领取, 这个数可能是当前日期, 也可能是签到总天数(这个不好试, 除非谁专门空一天不签到, 才能知道这个到底是啥)

安卓抓包麻烦, 不root就不能装根证书

**Comment by Zxr112553438** [comment]
![7436E5C2-5E33-4006-BD9A-B840BC23B7F5](https://user-images.githubusercontent.com/93114244/229189856-a5d62652-1454-4728-b813-ab74b23b295a.png)
![A2A109A3-646E-4614-B286-68AC7AC23E51](https://user-images.githubusercontent.com/93114244/229189881-cceab188-a265-4cee-a66a-4149a19f46db.png)
推送消息签到成功，说没有奖励，但是今天4.1有会员卡1天，奖励也没领

**Comment by Zxr112553438** [comment]
@ImYrS

**Comment by YJLX-dmj** [comment]
同样今天才四月一号，却显示签到两天，奖励没领取
![QQ截图20230401080118](https://user-images.githubusercontent.com/69313368/229255170-16530af4-5ba5-4750-bd31-9a13b82e936b.png)

**Comment by ImYrS** [comment]
> 想象一个问题，并不是每天都需要用到阿里云的吧。那么签到后的vip 延期卡 也就只有在需要的时候才会领取使用。
> 所以 签到之后的领取能不能设为可选，默认只签到

已经在 [v1.5.1](https://github.com/ImYrS/aliyun-auto-signin/releases/tag/v1.5.1) 支持仅签到功能.

但暂时不能在 Action 中使用, 等待下个小版本更新.

**Comment by ImYrS** [comment]
已经在 [v1.5.2](https://github.com/ImYrS/aliyun-auto-signin/releases/tag/v1.5.2) 支持 Action 仅签到功能.

参考最新的 How-To-Use-Action 配置即可使用. 默认每个月最后一天领取全部奖励

**Comment by at2008** [comment]
> 已经在 [v1.5.2](https://github.com/ImYrS/aliyun-auto-signin/releases/tag/v1.5.2) 支持 Action 仅签到功能.
> 
> 参考最新的 How-To-Use-Action 配置即可使用. 默认每个月最后一天领取全部奖励

最后一天？如果中间漏签，或者签到失败，会不会奖励都不领了？
能不能每次签到、领奖后检查一下是否已领取奖励？
感谢作者的辛苦付出！

**Comment by ImYrS** [comment]
> 最后一天？如果中间漏签，或者签到失败，会不会奖励都不领了？
> 
> 能不能每次签到、领奖后检查一下是否已领取奖励？
> 
> 感谢作者的辛苦付出！

只有配置了 “仅签到” 才是最后一天领取。

**Comment by Zxr112553438** [comment]
![image](https://user-images.githubusercontent.com/93114244/229298447-03e81ae0-a327-41a6-9187-b699af17d455.png)
![image](https://user-images.githubusercontent.com/93114244/229298488-2a556f13-9865-468d-82b4-c794bdd87253.png)
大佬，这个PUSHPLUS_TOPIC群组码是群组的token，还是这个群组编号 @ImYrS

**Comment by ImYrS** [comment]
@Zxr112553438 不相关的内容在单独的 issue 中提出
