### ISSUE TITLE
推送显示内容有误

### ISSUE THREAD

**Issue by YJLX-dmj** [ImYrS/aliyun-auto-signin#48]
推送显示签到失败，下面却显示本月全部签到，查看运行显示运行成功。 推送渠道：pushplus
![QQ截图20230331192019](https://user-images.githubusercontent.com/69313368/229107498-c3357b21-4389-43b5-8e07-74fe2441c2af.png)

**Comment by ImYrS** [comment]
是今天运行了两次签到脚本吗

**Comment by YJLX-dmj** [comment]
对，第一次失败了没有推送但是奖励却领取成功了，我自己又运行了一次就这样了。

**Comment by ImYrS** [comment]
这个符合运行逻辑, 是没问题的. 第一次其实签到成功了, 但是处理上有问题导致没有推送. 第二次发现已经全都签到了, 所以是签到失败
