### ISSUE TITLE
Server酱推送没有效果

### ISSUE THREAD

**Issue by exlulu** [ImYrS/aliyun-auto-signin#5]
Ubuntu 20.04.4 LTS
Python 3.11.2
本app版本 [fca5caa](https://github.com/ImYrS/aliyun-auto-signin/commit/fca5caa42bdeaf8c526eff2ffa5a4239003bc72e)

serverchan.py在modules目录里，没有收到推送，也试过把serverchan.py cp到跟app.py同一目录，也是没有推送结果，在Server酱主页里面测试过能正常推送的，请问是哪里设置不对吗？还是还有其他地方要设置？

**config.ini**
> \# refresh token
\# 阿里云盘 refresh token
refresh_token = qwert
\
\# access token data, do not change manually
\# 阿里云盘 access token 数据, 请不要手动修改
expired_at = 0
\
\# Push Notification
\# Supported: dingtalk, serverchan, pushdeer
\# Use comma (,) to separate multiple push methods
\# Leave blank if you don't want to use it
\# 签到结果推送
\# 支持: dingtalk, serverchan
\# 同时使用多个推送方式请用英文逗号 (,) 分隔
\# 不使用请留空
push_types = serverchan
\
\# DingTalk robot
dingtalk_app_key = ""
dingtalk_app_secret = ""
dingtalk_user_id = ""
\
\# ServerChan
serverchan_send_key = SCT12345
\
\# PushDeer
pushdeer_endpoint = https://api2.pushdeer.com
pushdeer_send_key = ""

**运行python app.py**
> lulu@ubuntu:~/aliyun-auto-signin$ python3.11 app.py 
2023-02-12 20:53:27,671 - app.py:188 - INFO: access_token 已过期, 正在更新...
2023-02-12 20:53:28,145 - app.py:84 - INFO: 签到成功, 本月累计签到 1 天.
2023-02-12 20:53:28,146 - app.py:85 - INFO: 本次签到 获得8TB超级会员体验卡

**Comment by ImYrS** [comment]
serverchan.py 就是在 modules 目录内.

试一下手动修改 serverchan.py:44 把 pusher.send() 函数传回的值接受一下, 打印出来看看.

**Comment by ImYrS** [comment]
由于在 [1e44d83](https://github.com/ImYrS/aliyun-auto-signin/commit/1e44d83d6c0925a1ee6c71e248456c53d99f90b7) 中添加了可同时配置多个推送渠道的 feature 导致处理配置单个推送渠道时出现了判断问题. 已在 [d4a2595](https://github.com/ImYrS/aliyun-auto-signin/commit/d4a25959ba06939a56964fbc08aa2b645eb30e48) 修复.

**Comment by exlulu** [comment]
谢大佬，好勤快呀
