### ISSUE TITLE
4月号显示本月签到第二天   且没有领取奖励

### ISSUE THREAD

**Issue by 294910541** [ImYrS/aliyun-auto-signin#50]

**Comment by ImYrS** [comment]
检查 #49

**Comment by 294910541** [comment]
你好   用的Actions怎么处理啊？

**Comment by ImYrS** [comment]
重新运行即可

**Comment by 294910541** [comment]
重新运行了一样的  还是签到第二天   无奖励

**Comment by ImYrS** [comment]
配置文件贴上来, 有没有报错贴上来.

**Comment by 294910541** [comment]
![image](https://user-images.githubusercontent.com/99067166/229258427-719d9e34-6fec-4001-be7a-1591c8dac41b.png)
![image](https://user-images.githubusercontent.com/99067166/229258443-41780ff9-3b3b-410b-b8d5-3abfbe719c61.png)

**Comment by ImYrS** [comment]
现在再重新运行一下试试

**Comment by 294910541** [comment]
![image](https://user-images.githubusercontent.com/99067166/229258549-26d09e0e-5397-45f6-b6ec-ac1a1d839665.png)
这次提示正常了   但是我已经手动领了 。明天再试试行不行   谢谢大佬！！！
