### ISSUE TITLE
PUSHPLUS_TOPIC群组码是群组的token，还是这个群组编号

### ISSUE THREAD

**Issue by Zxr112553438** [ImYrS/aliyun-auto-signin#51]
![1680363171119](https://user-images.githubusercontent.com/93114244/229298689-df7d4c85-c508-4892-ba21-35e7830941ab.jpg)
![1680363171132](https://user-images.githubusercontent.com/93114244/229298692-34fa5dd6-bf17-4dda-a03c-dd484725110a.jpg)

大佬，这个PUSHPLUS_TOPIC群组码是群组的token，还是这个群组编号 @ImYrS

**Comment by ImYrS** [comment]
应该是群组编号吧。需要 @exlulu 确认下.

**Comment by Zxr112553438** [comment]
我测试了，就是那个群组编号

**Comment by Zxr112553438** [comment]
不是token

**Comment by Zxr112553438** [comment]
> 应该是群号吧。需要@exlulu确认下。

我测试了，就是群组编号，不是token
