### ISSUE TITLE
【建议】请求适配这个私有框架，操作简单，云端运行

### ISSUE THREAD

**Issue by Zxr112553438** [ImYrS/aliyun-auto-signin#57]
![e69cb7646120ef75bdefc7b148a363d](https://user-images.githubusercontent.com/93114244/231224210-1bb5bf7f-4a63-4a8d-b7bf-e46b2299c7be.png)
![1eedace034421bea49fd69389cc2f8c](https://user-images.githubusercontent.com/93114244/231224229-f81b297b-a520-49d5-a8ad-d2c121887df0.png)
![b2a7dcb02fbac13a26ab4e1635688f3](https://user-images.githubusercontent.com/93114244/231224243-5733d56c-b79e-486d-9212-506e2ac84964.png)
  大佬可以考虑适配一下这个私有框架吗？而且里面有很多公开脚本
网站：http://krystal033.tk/

**Comment by Zxr112553438** [comment]
@ImYrS

**Comment by ImYrS** [comment]
简单看了下，没太理解这玩意啊...

**Comment by Zxr112553438** [comment]
> 简单看了下，没太理解这玩意啊...

啊哈哈哈哈哈

**Comment by chengnan049** [comment]
@Zxr112553438 https://github.com/qiandao-today/qiandao/ 项目是这个，或许对你有帮助

**Comment by chengnan049** [comment]
@Zxr112553438 我是在群里回复机器人的，所以默认@你了，实际上我想回复的是开发者。。。

**Comment by windy1021** [comment]
> ![e69cb7646120ef75bdefc7b148a363d](https://user-images.githubusercontent.com/93114244/231224210-1bb5bf7f-4a63-4a8d-b7bf-e46b2299c7be.png) ![1eedace034421bea49fd69389cc2f8c](https://user-images.githubusercontent.com/93114244/231224229-f81b297b-a520-49d5-a8ad-d2c121887df0.png) ![b2a7dcb02fbac13a26ab4e1635688f3](https://user-images.githubusercontent.com/93114244/231224243-5733d56c-b79e-486d-9212-506e2ac84964.png) 大佬可以考虑适配一下这个私有框架吗？而且里面有很多公开脚本 网站：http://krystal033.tk/

你好，请问下你还在用这个网站吗？之前从你这里了解到这个网站，但这个网站最近是不能用了吗？我打不开网站但我之前保存的签到脚本每天还在运行😅我想知道如果以后我想编辑或者停用该怎么办，现在联系不上该网站的管理人员，不知道你有没有什么方法
