### ISSUE TITLE
手动运行没有问题，但自动运行会说云盘的token无效

### ISSUE THREAD

**Issue by carson0718** [ImYrS/aliyun-auto-signin#59]
![image](https://user-images.githubusercontent.com/90074340/232258343-7e4267c7-71cf-4c15-892f-d167720ef760.png)

**Comment by carson0718** [comment]
![image](https://user-images.githubusercontent.com/90074340/232258449-49641349-6fc4-4353-90e9-977315471dbb.png)

**Comment by ImYrS** [comment]
@carson0718 暂时没有很好的解决办法，应该是阿里云盘官方问题
