### ISSUE TITLE
actions运行，签到成功，但是tgbot没有推送

### ISSUE THREAD

**Issue by troray** [ImYrS/aliyun-auto-signin#60]
也没提示错误。
`TELEGRAM_BOT_TOKEN`和`TELEGRAM_CHAT_ID` 也都正确填写了。

![](https://i.imgur.com/aW6uYUY.png)

**Comment by ImYrS** [comment]
@troray 看下 yml 配置

**Comment by troray** [comment]
> 

action.yml 默认没修改，是需要修改这个文件吗？我看文档中没有提到

**Comment by troray** [comment]
> @troray 看下 yml 配置

action.yml 默认没修改，是需要修改这个文件吗？我看文档中没有提到

**Comment by ImYrS** [comment]
@troray action 教程里面有提到，按需修改 PUSH_TYPES 参数

**Comment by troray** [comment]
> @troray action 教程里面有提到，按需修改 PUSH_TYPES 参数

确实有提到，是我大意了。
PUSH_TYPES: 'telegram'
这样没错吧。
另外，如果要启用仅签到, 不领取奖励，是需要把false改成true吗？
DO_NOT_REWARD: 'true'

**Comment by ImYrS** [comment]
@troray 对，但是不领取的话 可能会失效。如果没有特殊需求，还是自动领取比较好

**Comment by troray** [comment]
> @troray 对，但是不领取的话 可能会失效。如果没有特殊需求，还是自动领取比较好

明白，感谢指导。
