### ISSUE TITLE
签到成功，不推送

### ISSUE THREAD

**Issue by Zxr112553438** [ImYrS/aliyun-auto-signin#63]
![09142c84dad184be3782ffddfd6ce8a](https://user-images.githubusercontent.com/93114244/233789932-537d8bfc-0f3d-48fc-b938-49effe062d02.png)
![523d0303c27b53a94b8f685719b1fd2](https://user-images.githubusercontent.com/93114244/233789948-bb6229b3-c346-4909-84f4-960416669f3f.png)
签到成功，推送toekn也设置了，脚本运行好像就没有推送

**Comment by ImYrS** [comment]
@Zxr112553438 检查 action 配置的 PUSH_TYPES 参数是不是没填

**Comment by Zxr112553438** [comment]
> @Zxr112553438检查动作 配置的PUSH_TYPES 参数是不是没有

这个参数设置的是什么呀？

**Comment by Zxr112553438** [comment]
![3ef48db22c1acac86b8826ff560df0b](https://user-images.githubusercontent.com/93114244/233790263-42f9e50b-87ce-4387-8d7c-11744867e1f6.png)
有

**Comment by ImYrS** [comment]
@Zxr112553438 仔细看教程 这个是控制推送渠道的，你空的肯定没推送啊

**Comment by Zxr112553438** [comment]
> @Zxr112553438仔细看教程这个是控制推送渠道的，你空的确定没有推送啊

不好意思，是我自己SB了

**Comment by ImYrS** [comment]
@Zxr112553438

**Comment by Zxr112553438** [comment]
> @Zxr112553438

麻烦了大佬，是我自己的问题

**Comment by chengnan049** [comment]
So ，该 Issues 可以关闭了
