### ISSUE TITLE
[功能请求]自动领取签到奖励

### ISSUE THREAD

**Issue by chengnan049** [ImYrS/aliyun-auto-signin#64]
请求增加签到奖励领取接口，这里提供下思路，麻烦大佬了！ https://github.com/mrabit/aliyundriveDailyCheck/commit/da4240d00abf156d2d1863516ecc426cc4714e57

**Comment by ImYrS** [comment]
@chengnan049 有领取奖励功能呀

**Comment by chengnan049** [comment]
沙雕了，还没对项目进行实践就来提了，我看 Readme 没写还以为没有，打扰了大佬

**Comment by ImYrS** [comment]
@chengnan049 最开始是签到就会领取奖励，后来有接口变动，才分离签到和领取奖励。不过这个都做了好久了，他们的仓库改的还晚一些

**Comment by ImYrS** [comment]
@chengnan049 最早在这个 commit 就分开了 https://github.com/ImYrS/aliyun-auto-signin/commit/bc4c941ecf8e8c8f476e57814784110aa2c52778
