### ISSUE TITLE
能不能成功才推送消息？

### ISSUE THREAD

**Issue by CoderTonyChan** [ImYrS/aliyun-auto-signin#67]
因为不知道收到的是成功还是失败

**Comment by ImYrS** [comment]
@CoderTonyChan 签到失败会有提示的呀

**Comment by CoderTonyChan** [comment]
> @CoderTonyChan 签到失败会有提示的呀

ServerChan好似需要点进去 看了一下好似不支持显示在“通知内容” 每次都点进去才知道是否确实签了 这个月又没签满了/(ㄒoㄒ)/~~

**Comment by ImYrS** [comment]
@CoderTonyChan 这个没办法, 如果失败不推送, 更大概率不记得这个事情

**Comment by exlulu** [comment]
> > @CoderTonyChan 签到失败会有提示的呀
> 
> ServerChan好似需要点进去 看了一下好似不支持显示在“通知内容” 每次都点进去才知道是否确实签了 这个月又没签满了/(ㄒoㄒ)/~~

这个是Server酱的限制，有条件的话订阅支持一下作者或者使用其他推送平台，比如Telegram 机器人就能直接显示内容。
现在无论成功失败都推送还有一个作用，如果没有收到推送，大概率脚本运行出状况了

![sj](https://github.com/ImYrS/aliyun-auto-signin/assets/35789196/e01da224-1e85-4589-93f6-5ffdd9616788)
