### ISSUE TITLE
昨天不知道为什么没有成功签到，也没有推送

### ISSUE THREAD

**Issue by hapig** [ImYrS/aliyun-auto-signin#68]
之前都正常的，昨天运行到214那里就cancle了。
![image](https://github.com/ImYrS/aliyun-auto-signin/assets/50287824/3bc4765f-9c38-4c4b-abba-8ba9b99686e5)

**Comment by hapig** [comment]
不过刚刚手工运行了action，又正常运行了，奇怪。

**Comment by tony252** [comment]
有可能被ali那边拦截，拒绝访问了
我这个token是有效的，过了一段时间，手动执行就OK了
建议至少设置2次定时任务吧
如果是在私有的机器，貌似就不会有这样奇怪的问题
![image](https://github.com/ImYrS/aliyun-auto-signin/assets/26830193/8ebe3732-478c-44e1-8777-2e8e8fd7e7c7)
