### ISSUE TITLE
刚获取的token马上失效了

### ISSUE THREAD

**Issue by Zxr112553438** [ImYrS/aliyun-auto-signin#69]
![image](https://github.com/ImYrS/aliyun-auto-signin/assets/93114244/ff6dedab-3da1-4d96-94a7-7b42dc81f591)
刚获取的toekn，签到就失效了，二次获取，还是失效，是有什么原因呐 @ImYrS

**Comment by ImYrS** [comment]
@Zxr112553438 可以在本地环境，开 debug 写个测试脚本试试直接调用代码看看啥情况

**Comment by Zxr112553438** [comment]
> @Zxr112553438可以在本地环境，开debug写个测试脚本测试直接调用代码看什么情况

这个.......不懂呀

**Comment by Zxr112553438** [comment]
![image](https://github.com/ImYrS/aliyun-auto-signin/assets/93114244/2fd29ea7-e27a-4d94-8369-0794318a46d2)
同一个token，用的青龙面板其它博主分享的脚本运行是签到成功没问题
咱这脚本运行token确实失效的，哥，应该是咱这源码......是否麻烦看看调试一下？

**Comment by adair-hk** [comment]
@Zxr112553438 用PC获取的TOKEN试试

**Comment by Zxr112553438** [comment]
> @Zxr112553438 用PC获取的TOKEN试试
是用的PC浏览器获取的

**Comment by ImYrS** [comment]
@Zxr112553438 但我这边运行的一直没有问题，你要是方便的话，可以进 tg 交流群沟通下

**Comment by JerryLvTvT** [comment]
实测使用Chrome浏览器开发者控制台手动获取refresh_token成功签到，Alist项目这里好像不合适

**Comment by ImYrS** [comment]
@JerryLvTvT alist 获取的是阿里云盘开放平台的 token, 不是个人账号请求的 token
