### ISSUE TITLE
用Github Ation获取token失效

### ISSUE THREAD

**Issue by JeffreyLv233** [ImYrS/aliyun-auto-signin#71]

**Comment by ImYrS** [comment]
@JerryLvTvT 怎么个失效法？

**Comment by JerryLvTvT** [comment]
Action成功，但无签到

**Comment by ImYrS** [comment]
@JerryLvTvT 放日志…

**Comment by JerryLvTvT** [comment]
![BUG](https://github.com/ImYrS/aliyun-auto-signin/assets/118607142/8aef156f-408a-46d7-b41f-547dab3704bb)

**Comment by ImYrS** [comment]
@JerryLvTvT 点进去看日志

**Comment by JerryLvTvT** [comment]
![Uploading log.png…]()

**Comment by JerryLvTvT** [comment]
![log](https://github.com/ImYrS/aliyun-auto-signin/assets/118607142/19a06405-5bd5-4232-8044-4e7338df591b)

**Comment by JerryLvTvT** [comment]
emmmmm，“refresh token无效”

**Comment by ImYrS** [comment]
@JerryLvTvT 换 token 就好啦

**Comment by JerryLvTvT** [comment]
2023-06-04 11:10:39,364 - app.py:90 - ERROR: [eyJ0********************************************************************************************************************************************************************************************************************************************************************************dxnw] 获取 access token 失败, 可能是 refresh token 无效.

**Comment by JerryLvTvT** [comment]
:(

**Comment by ImYrS** [comment]
@JerryLvTvT 重新获取 token 更新进去

**Comment by JerryLvTvT** [comment]
对啊

**Comment by JerryLvTvT** [comment]
貌似一个原因
![BUG](https://github.com/ImYrS/aliyun-auto-signin/assets/118607142/2ebf01f0-6794-48ea-abd6-05cc91800ec4)

**Comment by JerryLvTvT** [comment]
是不是这个原因
![BUG](https://github.com/ImYrS/aliyun-auto-signin/assets/118607142/0d250297-8dc6-45ed-b5eb-479ab49c68da)

**Comment by JerryLvTvT** [comment]
实测使用Chrome浏览器开发者控制台手动获取refresh_token成功签到，Alist项目这里好像不合适
