### ISSUE TITLE
Github Action workflow failed with API rate limit error.

### ISSUE THREAD

**Issue by ulion** [ImYrS/aliyun-auto-signin#75]
API rate limit exceeded for 40.75.119.50. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

Rerun the job, it works with no error this time. So this error may cause the check-in unstable and unexpected failed randomly? any hints to overcome it?

**Comment by ImYrS** [comment]
Requesting GitHub API with `Personal Access Token` should solve this problem. I will address this issue when time permits, but feel free to submit pull requests as well.

**Comment by ulion** [comment]
No idea, in the current repo code, github requests are all requested with GP_TOKEN, and it is a `Personal access token`

**Comment by ImYrS** [comment]
@ulion Actually the clone action is not with GitHub token.

**Comment by ImYrS** [comment]
fixed in [v1.5.5](https://github.com/ImYrS/aliyun-auto-signin/releases/tag/v1.5.5)
