### ISSUE TITLE
运行失败后手动运行成功了，这是为什么

### ISSUE THREAD

**Issue by yeyudoc** [ImYrS/aliyun-auto-signin#77]
![image](https://github.com/ImYrS/aliyun-auto-signin/assets/83936435/1cbb4142-d1f3-485f-b172-e654cd40fe72)
失败后，能否增加隔一分钟重试的功能

**Comment by ImYrS** [comment]
@yeyudoc 把失败日志贴上来

**Comment by yeyudoc** [comment]
API rate limit exceeded for 40.75.119.49. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

**Comment by yeyudoc** [comment]
@ImYrS

**Comment by ImYrS** [comment]
和 #75 一个问题, 合并处理
