### ISSUE TITLE
关于取消 Do Not Reward 模式的计划的讨论

### ISSUE THREAD

**Issue by ImYrS** [ImYrS/aliyun-auto-signin#78]
~Do Not Reward 又称仅签到不领取奖励, 此模式由于维护问题和兑换校验难度高等问题将被取消.~

### 时间节点 (已弃用)

~- 2023-06-01 确认计划取消 Do Not Reward Mode.~
~- 2023-06-13 使用该模式的用户签到推送中将包含模式取消提醒.~
~- 2023-07-01 不再读取 GitHub Actions 模式下的 `DO_NOT_REWARD` flag.~
~- 2023-07-05 取消本地运行模式下的 `--do-not-reward` flag.~
~- 2023-07-05 彻底移除 Do Not Reward Mode 相关代码.~

### 后续

新平台已经进入公测: [立即注册](https://ap.imyrs.cn)

### 意见和建议

欢迎在此 issue 下提出对此功能的建议.

**Comment by CJYKK** [comment]
可以不回答，只是想提个问（
1. 既然维护困难，那为什么不停止维护呢？
2. 可以标一个“已弃用”标签，不用非要删了 啊
3. 新的平台何时完成？基于什么编程语言？
以上。

**Comment by adair-hk** [comment]
这个功能我觉得非常好，目前使用来说没什么问题，不知道是否有人因为到期没领到所以造成了困扰？能不能下个版本也继续保留这个功能？

**Comment by ImYrS** [comment]
@CJYKK 1. 现在就是准备停止维护了.

2. 我认为既然已经弃用并不维护了, 应该可以删掉了. 如果确认要使用, 可以采用指定旧版本运行的方法.

3. 新的平台上线时间还未定, 可能不是开源项目, 因为可以被人拿去代挂赚钱. 后端基于 Python.

**Comment by ImYrS** [comment]
@adair-hk 现在主要的问题可能就是月末自动领取全部未领取奖励这个子功能, 很难维护和验证 (一个月只有一天). 这个功能我自己没有用, 也不太清楚实际效果. 所以在考虑去掉. 如果一定保留这个 do not reward mode, 那月末自动领取全部奖励这个子功能我可能也会去掉.

**Comment by qhmorz** [comment]
本来觉得挺好用的  结果没用几个月就停止维护了  感觉有点可惜

**Comment by CJYKK** [comment]
> @CJYKK 1. 现在就是准备停止维护了.
> 
> 2. 我认为既然已经弃用并不维护了, 应该可以删掉了. 如果确认要使用, 可以采用指定旧版本运行的方法.
> 
> 3. 新的平台上线时间还未定, 可能不是开源项目, 因为可以被人拿去代挂赚钱. 后端基于 Python.

啊对了，请问一下
Actions里能指定版本吗，还是必须跟着最新的走？

**Comment by ImYrS** [comment]
@CJYKK 如果确定移除 do not reward 那会开发指定版本的功能，现在默认就是最新

**Comment by adair-hk** [comment]
> @adair-hk 现在主要的问题可能就是月末自动领取全部未领取奖励这个子功能, 很难维护和验证 (一个月只有一天). 这个功能我自己没有用, 也不太清楚实际效果. 所以在考虑去掉. 如果一定保留这个 do not reward mode, 那月末自动领取全部奖励这个子功能我可能也会去掉.

能不能采用最后一天的不同时段尝试领取这样？我现在签到就是定了两个时间段，以防止漏签

**Comment by yanbinxiao** [comment]
大佬，这个功能很有用，而且目前使用起来并没有什么问题啊，强烈推荐保留

**Comment by ImYrS** [comment]
@yanbinxiao 月底自动领取全部奖励这个功能是有效的吗

**Comment by yanbinxiao** [comment]
> @yanbinxiao 月底自动领取全部奖励这个功能是有效的吗

我这边使用是正常的，既然这个功能是可以通过配置开关的，保留应该也没啥问题吧

**Comment by ImYrS** [comment]
@yanbinxiao 好的，会考虑的

**Comment by Episode233** [comment]
建议还是保留一下吧，有时候恰巧需要看视频结果既没有影音卡也没有会员卡是真的难受，没错，就是刚刚被迫开通会员的我，540p是真的恶心人:(

**Comment by Exlany** [comment]
> @yanbinxiao 月底自动领取全部奖励这个功能是有效的吗

我这边也是有效了，已经用了几个月了

**Comment by CJYKK** [comment]
> @yanbinxiao 月底自动领取全部奖励这个功能是有效的吗

功能是有效的，但是逻辑好像是检测已签到的天数，而不是当天是几号
这就导致如果断签了一天，月末的时候就不会自动领奖励了……

**Comment by Loli0721** [comment]
我也建议保留，影视和会员卡这种东西在用得到的情况下领取才能起到作用，否则就是浪费了，或者有没有办法实现只领取续期卡不领取影视和会员卡？如果月末一次性领取功能真的容易出错的话

**Comment by aixiu** [comment]
我也是有效的，至少在6月底都是正常使用。
