### ISSUE TITLE
cookie中没有refresh token

### ISSUE THREAD

**Issue by autumndays** [ImYrS/aliyun-auto-signin#79]
最近阿里云盘账户登录后，找不到或者说取消了refresh token。

**Comment by ImYrS** [comment]
@autumndays token 不在 cookie 里面

**Comment by autumndays** [comment]
> @autumndays token 不在 cookie 里面

请问到哪里获取refresh token？

**Comment by autumndays** [comment]
<img width="614" alt="image" src="https://github.com/ImYrS/aliyun-auto-signin/assets/37567171/dc6f5c7a-8b68-4ebf-bc78-9ff0059f074a">
已找到

**Comment by ImYrS** [comment]
@autumndays 可以使用 https://ali-qr.imyrs.cn 扫码获取
