### ISSUE TITLE
可否支持青龙定时任务

### ISSUE THREAD

**Issue by mima454188** [ImYrS/aliyun-auto-signin#8]
![image](https://user-images.githubusercontent.com/74166821/219939318-e77e074a-76b4-48eb-930f-ad505ae7f0d0.png)
两次手动尝试 哈哈哈，请问大佬能否支持青龙定时自动签到呢？
另外推送我是不是填错了还是收不到
![image](https://user-images.githubusercontent.com/74166821/219939440-105f1519-e42f-4c46-9f72-cd5958089e16.png)

**Comment by ImYrS** [comment]
@mima454188 config 的 push_types 也要填上 pushplus

青龙面板没用过，按道理写个 python 运行的命令就可以了

**Comment by mima454188** [comment]
> 

感谢！push_types 填上之后就好了 。
![image](https://user-images.githubusercontent.com/74166821/219939886-af1b3107-92db-4d14-80f7-6b31e84d62d1.png)

**Comment by mima454188** [comment]
> @mima454188 config 的 push_types 也要填上 pushplus
> 
> 青龙面板没用过，按道理写个 python 运行的命令就可以了

![image](https://user-images.githubusercontent.com/74166821/219940011-6f4f27e1-27bc-47d3-a306-818208f1dba7.png)
青龙里面安装了这个依赖，不知道能不能运行

**Comment by ImYrS** [comment]
@mima454188 还要安装 configObj

**Comment by mima454188** [comment]
> configObj

![image](https://user-images.githubusercontent.com/74166821/219940128-ebedb9dc-ce6b-4474-ba18-2c2928d5d1b6.png)
可以安装上

**Comment by mima454188** [comment]
@ImYrS  大佬 我成功了，这样设好定时直接不用管了
![image](https://user-images.githubusercontent.com/74166821/219940910-58665e52-7f89-4b50-9b06-d7c24ecf8fc5.png)

**Comment by ImYrS** [comment]
@mima454188 方便的话写个简单的流程或者教程？我贴进 readme

**Comment by mima454188** [comment]
@ImYrS  方便加v ？jiayouabin2010 我把我的操作给你

**Comment by mima454188** [comment]
@ImYrS  先安装两个依赖，我之前拉你github的库发现拉不到配置配置文件，所以就我直接下载了releases。在本地配置好，然后上传青龙面板 task 拉一下脚本 就运行成功了

**Comment by gewasli** [comment]
Traceback (most recent call last):
  File "/ql/data/scripts/ImYrS_aliyun-auto-signin_main/app.py", line 17, in <module>
    from modules import dingtalk, serverchan, pushdeer, telegram, pushplus
ImportError: cannot import name 'dingtalk' from 'modules' (/usr/local/lib/python3.10/site-packages/modules.py)
我直接在订阅里面拉取的，但是一直报错。

**Comment by gewasli** [comment]
> 回溯（最近一次调用）：文件“/ql/data/scripts/ImYrS_aliyun-auto-signin_main/app.py”，第 17 行，从模块导入 dingtalk， serverchan， pushdeer， telegram， pushplus 导入错误： 无法从 'modules' 导入名称 'dingtalk' （/usr/local/lib/python3.10/site-packages/modules.py） 我直接在订阅里面拉取的，但是一直报错。

删除“from modules import dingtalk, serverchan, pushdeer, telegram, pushplus”这一句可以正常使用

**Comment by gewasli** [comment]
> > 回溯（最近一次调用）：文件“/ql/data/scripts/ImYrS_aliyun-auto-signin_main/app.py”，第 17 行，从模块导入 dingtalk， serverchan， pushdeer， telegram， pushplus 导入错误： 无法从 'modules' 导入名称 'dingtalk' （/usr/local/lib/python3.10/site-packages/modules.py） 我直接在订阅里面拉取的，但是一直报错。
> 
> 删除“from modules import dingtalk, serverchan, pushdeer, telegram, pushplus”这一句可以正常使用

找到原因了，我原本有个modules模块，脚本直接调用了这个模块，模块内没有“dingtalk, serverchan, pushdeer, telegram, pushplus”就出错了。

**Comment by ImYrS** [comment]
现已支持 GitHub Action 定时运行, 无需服务器
