### ISSUE TITLE
python3.11.3运行报No module named '_cffi_backend'

### ISSUE THREAD

**Issue by xiatao** [ImYrS/aliyun-auto-signin#81]
使用python3.11.3运行报No module named '_cffi_backend'

**Comment by ImYrS** [comment]
@xiatao pip install cffi

环境问题建议百度解决

**Comment by xiatao** [comment]
cffi安装过了还是不行

**Comment by ImYrS** [comment]
@xiatao 建议使用 actions, 环境问题不好解决

**Comment by xiatao** [comment]
收到，马上尝试一下GitHub Action，感谢您的回答与鼓励~

**Comment by xiatao** [comment]
使用GitHub Action已经成功签到并且推送通知了，再次感谢！
