### ISSUE TITLE
【建议】加个签到失败或者运行异常推送消息的开关

### ISSUE THREAD

**Issue by carldats** [ImYrS/aliyun-auto-signin#84]
【建议】加个签到失败或者运行异常推送消息的开关
正常签到每天都收到消息感觉太频繁了，能不能签到失败的时候推送消息，其他情况不推送消息？

**Comment by ImYrS** [comment]
actions 运行失败的可能原因太多, 很多情况是在程序初始化之前就失败了, 没办法做到失败推送. 唯一能拦截错误的就是签到请求, 但这一步其实失败的概率较低. 可以尝试一下正在开发的 [新签到平台](https://ap.imyrs.cn), 支持仅在签到失败的时候才推送.
