### ISSUE TITLE
获取配置失败

### ISSUE THREAD

**Issue by Eternal-Future** [ImYrS/aliyun-auto-signin#90]
![Screenshot_2023-08-16-01-38-45-602_mark via](https://github.com/ImYrS/aliyun-auto-signin/assets/88213964/29b5a4be-3c79-4b42-9675-81876090aaf2)
嗯...就获取配置失败 排除Refresh_Token的问题，它一直在更新 昨天运行还好好的，今天github发邮件说运行失败
![Screenshot_2023-08-16-01-38-29-511_mark via](https://github.com/ImYrS/aliyun-auto-signin/assets/88213964/c07ecf30-d6da-4401-8b56-2bc4a6ddb5d1)

**Comment by ImYrS** [comment]
现在再试试?

**Comment by Eternal-Future** [comment]
现在可以了
