### ISSUE TITLE
后台显示脚本运行失败  反复手动重试也是一样的报错

### ISSUE THREAD

**Issue by qhmorz** [ImYrS/aliyun-auto-signin#93]
报错内容如下 
![Screenshot_2023-08-29-07-49-01-382_com microsoft emmx-edit](https://github.com/ImYrS/aliyun-auto-signin/assets/96979347/8a17fd50-611a-44a4-bdec-c8ef3a143c08)

**Comment by haveonename** [comment]
我这边也是同样的错误

**Comment by Y-7-0101** [comment]
me too

**Comment by haveonename** [comment]
已恢复正常；
我估计是git本身的问题，我尝试用wget下载其它项目的代码也是同样的错误；

**Comment by ImYrS** [comment]
目测是 GitHub 异常, 尚未有更多错误汇报
